/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Genre = IDL.Variant({
  'SciFi' : IDL.Null,
  'Adventure' : IDL.Null,
  'Action' : IDL.Null,
  'Drama' : IDL.Null,
  'School' : IDL.Null,
  'Romance' : IDL.Null,
  'Supernatural' : IDL.Null,
  'Fantasy' : IDL.Null,
  'Comedy' : IDL.Null,
});
export const CreateVideoRequest = IDL.Record({
  'title' : IDL.Text,
  'episodeCount' : IDL.Nat,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'coverImage' : ExternalBlob,
  'genre' : Genre,
});
export const AdminDashboard = IDL.Record({
  'genreCounts' : IDL.Vec(IDL.Tuple(Genre, IDL.Nat)),
  'totalVideos' : IDL.Nat,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'episodeCount' : IDL.Nat,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'coverImage' : ExternalBlob,
  'genre' : Genre,
  'uploadedAt' : IDL.Int,
});
export const UpdateVideoRequest = IDL.Record({
  'title' : IDL.Text,
  'episodeCount' : IDL.Nat,
  'description' : IDL.Text,
  'coverImage' : ExternalBlob,
  'genre' : Genre,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoSummary = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'episodeCount' : IDL.Nat,
  'coverImage' : ExternalBlob,
  'genre' : Genre,
  'uploadedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addToWatchlist' : IDL.Func([VideoId], [], []),
  'adminCreateVideo' : IDL.Func([CreateVideoRequest], [VideoId], []),
  'adminDeleteVideo' : IDL.Func([VideoId], [IDL.Bool], []),
  'adminGetDashboard' : IDL.Func([], [AdminDashboard], ['query']),
  'adminListVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'adminUpdateVideo' : IDL.Func([VideoId, UpdateVideoRequest], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyWatchlist' : IDL.Func([], [IDL.Vec(VideoSummary)], ['query']),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listVideos' : IDL.Func([], [IDL.Vec(VideoSummary)], ['query']),
  'listVideosByGenre' : IDL.Func([Genre], [IDL.Vec(VideoSummary)], ['query']),
  'removeFromWatchlist' : IDL.Func([VideoId], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoSummary)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Genre = IDL.Variant({
    'SciFi' : IDL.Null,
    'Adventure' : IDL.Null,
    'Action' : IDL.Null,
    'Drama' : IDL.Null,
    'School' : IDL.Null,
    'Romance' : IDL.Null,
    'Supernatural' : IDL.Null,
    'Fantasy' : IDL.Null,
    'Comedy' : IDL.Null,
  });
  const CreateVideoRequest = IDL.Record({
    'title' : IDL.Text,
    'episodeCount' : IDL.Nat,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'coverImage' : ExternalBlob,
    'genre' : Genre,
  });
  const AdminDashboard = IDL.Record({
    'genreCounts' : IDL.Vec(IDL.Tuple(Genre, IDL.Nat)),
    'totalVideos' : IDL.Nat,
  });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'episodeCount' : IDL.Nat,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'coverImage' : ExternalBlob,
    'genre' : Genre,
    'uploadedAt' : IDL.Int,
  });
  const UpdateVideoRequest = IDL.Record({
    'title' : IDL.Text,
    'episodeCount' : IDL.Nat,
    'description' : IDL.Text,
    'coverImage' : ExternalBlob,
    'genre' : Genre,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoSummary = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'episodeCount' : IDL.Nat,
    'coverImage' : ExternalBlob,
    'genre' : Genre,
    'uploadedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addToWatchlist' : IDL.Func([VideoId], [], []),
    'adminCreateVideo' : IDL.Func([CreateVideoRequest], [VideoId], []),
    'adminDeleteVideo' : IDL.Func([VideoId], [IDL.Bool], []),
    'adminGetDashboard' : IDL.Func([], [AdminDashboard], ['query']),
    'adminListVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'adminUpdateVideo' : IDL.Func(
        [VideoId, UpdateVideoRequest],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyWatchlist' : IDL.Func([], [IDL.Vec(VideoSummary)], ['query']),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listVideos' : IDL.Func([], [IDL.Vec(VideoSummary)], ['query']),
    'listVideosByGenre' : IDL.Func([Genre], [IDL.Vec(VideoSummary)], ['query']),
    'removeFromWatchlist' : IDL.Func([VideoId], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(VideoSummary)], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };