/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDashboard {
  'genreCounts' : Array<[Genre, bigint]>,
  'totalVideos' : bigint,
}
export interface CreateVideoRequest {
  'title' : string,
  'episodeCount' : bigint,
  'description' : string,
  'videoFile' : ExternalBlob,
  'coverImage' : ExternalBlob,
  'genre' : Genre,
}
export type ExternalBlob = Uint8Array;
export type Genre = { 'SciFi' : null } |
  { 'Adventure' : null } |
  { 'Action' : null } |
  { 'Drama' : null } |
  { 'School' : null } |
  { 'Romance' : null } |
  { 'Supernatural' : null } |
  { 'Fantasy' : null } |
  { 'Comedy' : null };
export interface UpdateVideoRequest {
  'title' : string,
  'episodeCount' : bigint,
  'description' : string,
  'coverImage' : ExternalBlob,
  'genre' : Genre,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : VideoId,
  'title' : string,
  'episodeCount' : bigint,
  'description' : string,
  'videoFile' : ExternalBlob,
  'coverImage' : ExternalBlob,
  'genre' : Genre,
  'uploadedAt' : bigint,
}
export type VideoId = bigint;
export interface VideoSummary {
  'id' : VideoId,
  'title' : string,
  'episodeCount' : bigint,
  'coverImage' : ExternalBlob,
  'genre' : Genre,
  'uploadedAt' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addToWatchlist' : ActorMethod<[VideoId], undefined>,
  'adminCreateVideo' : ActorMethod<[CreateVideoRequest], VideoId>,
  'adminDeleteVideo' : ActorMethod<[VideoId], boolean>,
  'adminGetDashboard' : ActorMethod<[], AdminDashboard>,
  'adminListVideos' : ActorMethod<[], Array<Video>>,
  'adminUpdateVideo' : ActorMethod<[VideoId, UpdateVideoRequest], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyWatchlist' : ActorMethod<[], Array<VideoSummary>>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listVideos' : ActorMethod<[], Array<VideoSummary>>,
  'listVideosByGenre' : ActorMethod<[Genre], Array<VideoSummary>>,
  'removeFromWatchlist' : ActorMethod<[VideoId], undefined>,
  'searchVideos' : ActorMethod<[string], Array<VideoSummary>>,
  'seedSampleData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];