/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Video {
    id: VideoId;
    title: string;
    episodeCount: bigint;
    description: string;
    videoFile: ExternalBlob;
    coverImage: ExternalBlob;
    genre: Genre;
    uploadedAt: bigint;
}
export interface CreateVideoRequest {
    title: string;
    episodeCount: bigint;
    description: string;
    videoFile: ExternalBlob;
    coverImage: ExternalBlob;
    genre: Genre;
}
export interface AdminDashboard {
    genreCounts: Array<[Genre, bigint]>;
    totalVideos: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type VideoId = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface VideoSummary {
    id: VideoId;
    title: string;
    episodeCount: bigint;
    coverImage: ExternalBlob;
    genre: Genre;
    uploadedAt: bigint;
}
export interface UpdateVideoRequest {
    title: string;
    episodeCount: bigint;
    description: string;
    coverImage: ExternalBlob;
    genre: Genre;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Genre {
    SciFi = "SciFi",
    Adventure = "Adventure",
    Action = "Action",
    Drama = "Drama",
    School = "School",
    Romance = "Romance",
    Supernatural = "Supernatural",
    Fantasy = "Fantasy",
    Comedy = "Comedy"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addToWatchlist(videoId: VideoId): Promise<void>;
    adminCreateVideo(req: CreateVideoRequest): Promise<VideoId>;
    adminDeleteVideo(id: VideoId): Promise<boolean>;
    adminGetDashboard(): Promise<AdminDashboard>;
    adminListVideos(): Promise<Array<Video>>;
    adminUpdateVideo(id: VideoId, req: UpdateVideoRequest): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getMyWatchlist(): Promise<Array<VideoSummary>>;
    getVideo(id: VideoId): Promise<Video | null>;
    isCallerAdmin(): Promise<boolean>;
    listVideos(): Promise<Array<VideoSummary>>;
    listVideosByGenre(genre: Genre): Promise<Array<VideoSummary>>;
    removeFromWatchlist(videoId: VideoId): Promise<void>;
    searchVideos(searchTerm: string): Promise<Array<VideoSummary>>;
    seedSampleData(): Promise<void>;
}
import type { AdminDashboard as _AdminDashboard, CreateVideoRequest as _CreateVideoRequest, ExternalBlob as _ExternalBlob, Genre as _Genre, UpdateVideoRequest as _UpdateVideoRequest, UserRole as _UserRole, Video as _Video, VideoId as _VideoId, VideoSummary as _VideoSummary, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addToWatchlist(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async adminCreateVideo(arg0: CreateVideoRequest): Promise<VideoId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateVideo(await to_candid_CreateVideoRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateVideo(await to_candid_CreateVideoRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async adminDeleteVideo(arg0: VideoId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteVideo(arg0);
            return result;
        }
    }
    async adminGetDashboard(): Promise<AdminDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDashboard();
                return from_candid_AdminDashboard_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDashboard();
            return from_candid_AdminDashboard_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListVideos(): Promise<Array<Video>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListVideos();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListVideos();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateVideo(arg0: VideoId, arg1: UpdateVideoRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateVideo(arg0, await to_candid_UpdateVideoRequest_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateVideo(arg0, await to_candid_UpdateVideoRequest_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWatchlist(): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWatchlist();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWatchlist();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideo(arg0: VideoId): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listVideos(): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVideos();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVideos();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVideosByGenre(arg0: Genre): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVideosByGenre(to_candid_Genre_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVideosByGenre(to_candid_Genre_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWatchlist(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async searchVideos(arg0: string): Promise<Array<VideoSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchVideos(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchVideos(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
}
function from_candid_AdminDashboard_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminDashboard): AdminDashboard {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Genre_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Genre): Genre {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_VideoSummary_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoSummary): Promise<VideoSummary> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Promise<Video | null> {
    return value.length === 0 ? null : await from_candid_Video_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    genreCounts: Array<[_Genre, bigint]>;
    totalVideos: bigint;
}): {
    genreCounts: Array<[Genre, bigint]>;
    totalVideos: bigint;
} {
    return {
        genreCounts: from_candid_vec_n15(_uploadFile, _downloadFile, value.genreCounts),
        totalVideos: value.totalVideos
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    episodeCount: bigint;
    description: string;
    videoFile: _ExternalBlob;
    coverImage: _ExternalBlob;
    genre: _Genre;
    uploadedAt: bigint;
}): Promise<{
    id: VideoId;
    title: string;
    episodeCount: bigint;
    description: string;
    videoFile: ExternalBlob;
    coverImage: ExternalBlob;
    genre: Genre;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        episodeCount: value.episodeCount,
        description: value.description,
        videoFile: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.videoFile),
        coverImage: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.coverImage),
        genre: from_candid_Genre_n17(_uploadFile, _downloadFile, value.genre),
        uploadedAt: value.uploadedAt
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VideoId;
    title: string;
    episodeCount: bigint;
    coverImage: _ExternalBlob;
    genre: _Genre;
    uploadedAt: bigint;
}): Promise<{
    id: VideoId;
    title: string;
    episodeCount: bigint;
    coverImage: ExternalBlob;
    genre: Genre;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        episodeCount: value.episodeCount,
        coverImage: await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.coverImage),
        genre: from_candid_Genre_n17(_uploadFile, _downloadFile, value.genre),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Genre, bigint]): [Genre, bigint] {
    return [
        from_candid_Genre_n17(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SciFi: null;
} | {
    Adventure: null;
} | {
    Action: null;
} | {
    Drama: null;
} | {
    School: null;
} | {
    Romance: null;
} | {
    Supernatural: null;
} | {
    Fantasy: null;
} | {
    Comedy: null;
}): Genre {
    return "SciFi" in value ? Genre.SciFi : "Adventure" in value ? Genre.Adventure : "Action" in value ? Genre.Action : "Drama" in value ? Genre.Drama : "School" in value ? Genre.School : "Romance" in value ? Genre.Romance : "Supernatural" in value ? Genre.Supernatural : "Fantasy" in value ? Genre.Fantasy : "Comedy" in value ? Genre.Comedy : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Genre, bigint]>): Array<[Genre, bigint]> {
    return value.map((x)=>from_candid_tuple_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VideoSummary>): Promise<Array<VideoSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_VideoSummary_n30(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateVideoRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateVideoRequest): Promise<_CreateVideoRequest> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Genre_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): _Genre {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateVideoRequest_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateVideoRequest): Promise<_UpdateVideoRequest> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    episodeCount: bigint;
    description: string;
    coverImage: ExternalBlob;
    genre: Genre;
}): Promise<{
    title: string;
    episodeCount: bigint;
    description: string;
    coverImage: _ExternalBlob;
    genre: _Genre;
}> {
    return {
        title: value.title,
        episodeCount: value.episodeCount,
        description: value.description,
        coverImage: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.coverImage),
        genre: to_candid_Genre_n11(_uploadFile, _downloadFile, value.genre)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    episodeCount: bigint;
    description: string;
    videoFile: ExternalBlob;
    coverImage: ExternalBlob;
    genre: Genre;
}): Promise<{
    title: string;
    episodeCount: bigint;
    description: string;
    videoFile: _ExternalBlob;
    coverImage: _ExternalBlob;
    genre: _Genre;
}> {
    return {
        title: value.title,
        episodeCount: value.episodeCount,
        description: value.description,
        videoFile: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.videoFile),
        coverImage: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.coverImage),
        genre: to_candid_Genre_n11(_uploadFile, _downloadFile, value.genre)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): {
    SciFi: null;
} | {
    Adventure: null;
} | {
    Action: null;
} | {
    Drama: null;
} | {
    School: null;
} | {
    Romance: null;
} | {
    Supernatural: null;
} | {
    Fantasy: null;
} | {
    Comedy: null;
} {
    return value == Genre.SciFi ? {
        SciFi: null
    } : value == Genre.Adventure ? {
        Adventure: null
    } : value == Genre.Action ? {
        Action: null
    } : value == Genre.Drama ? {
        Drama: null
    } : value == Genre.School ? {
        School: null
    } : value == Genre.Romance ? {
        Romance: null
    } : value == Genre.Supernatural ? {
        Supernatural: null
    } : value == Genre.Fantasy ? {
        Fantasy: null
    } : value == Genre.Comedy ? {
        Comedy: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
